
[specification]
content = '''
Create a REST API service with:
- User authentication using JWT tokens
- CRUD operations for a blog post resource
- Error handling with proper HTTP status codes
'''

[architecture]
content = '''
## Component: AuthService
Handles JWT token generation, validation, and user authentication.

## Component: BlogPostManager
Manages CRUD operations for blog posts with proper validation.

## Component: ErrorHandler
Provides standardized error handling with appropriate HTTP status codes.
'''

[pseudocode]
content = '''
AuthService:
- generate_token(user_data) -> str
- validate_token(token) -> dict
- authenticate_user(username, password) -> bool

BlogPostManager:
- create_post(user_id, title, content) -> Post
- get_post(post_id) -> Post
- update_post(post_id, updates) -> Post
- delete_post(post_id) -> bool

ErrorHandler:
- handle_auth_error() -> Response(401)
- handle_not_found() -> Response(404)
- handle_validation_error() -> Response(400)
'''
