# SPARC Framework Project Configuration

[project]
name = "supabase-devops-cli"
description = "swarm agents using denojs"
version = "0.1.0"

[architecture]
# Component organization
component_style = "PascalCase"
test_prefix = "test_"
source_suffix = ".py"

# Directory structure
src_dir = "src"
test_dir = "tests"
docs_dir = "docs"

[implementation]
# Code generation settings
max_attempts = 3
test_first = true
type_hints = true
docstring_style = "Google"

[testing]
# Testing requirements
min_coverage = 85
unit_test_required = true
integration_test_required = true

[quality]
# Code quality requirements
max_complexity = 8
max_line_length = 88
require_type_hints = true
require_docstrings = true

[security]
# Security requirements
require_input_validation = true
require_authentication = true
require_authorization = true

[deployment]
# Deployment configuration
containerize = true
ci_cd_required = true
monitoring_required = true
required_platforms = ["linux"]

[documentation]
# Documentation requirements
readme_required = true
api_docs_required = true
architecture_docs_required = true
changelog_required = true[specification]
content = """
Create a detailed specification for a swarm of autonomous agents using Deno.js, including:
- Agent communication and coordination
- Task distribution and management 
- State synchronization
- Error handling and recovery
"""

[pseudocode]
content = """
Provide high-level pseudocode for the main agent functionalities:
- Agent lifecycle management
- Communication protocols
- Task execution flows
- State management
"""

[architecture]
content = """
Describe the system architecture for a Deno.js-based agent swarm system:
- Core agent components
- Communication layer
- Task scheduling
- State management
- Monitoring and control
"""

[refinement]
content = """
Define optimization strategies for:
- Agent performance
- Communication efficiency
- Resource utilization
- System reliability
"""

[completion]
content = """
Specify completion criteria including:
- Performance benchmarks
- Testing requirements
- Deployment guidelines
- Monitoring setup
"""
